version: '3.3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    networks:
      - stomp
      - bridge
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    networks:
      - stomp      
      - bridge
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  stomp:
    driver: overlay
  bridge:
    external: true

